name: CMS Github Actions

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  fix-lint-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Go to app
        run: cd app
        shell: bash
      - name: NPM clean install
        run: npm ci
        shell: bash
        working-directory: ./app
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run Linter
        run: npm run lint
        shell: bash
        working-directory: ./app

  fix-lint-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Go to backend
        run: cd backend
        shell: bash
      - name: NPM clean install
        run: npm ci
        shell: bash
        working-directory: ./backend
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run Linter
        run: npm run lint
        shell: bash
        working-directory: ./backend
      - name: Run test
        run: npm test
        shell: bash
        working-directory: ./backend
