name: CMS Github Actions

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  fix-lint-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Go to app
        run: cd app
        shell: bash
      - name: Install dependency
        run: npm i
        shell: bash
      - name: NPM CI
        run: npm ci
        shell: bash
      - name: Print npm configuration
        run: npm config list
        shell: bash
      - name: Print npm configuration 2
        run: npm config ls -l
        shell: bash
      - name: npm run
        run: npm run
        shell: bash
      - name: npm run
        run: npm run start
        shell: bash
      - name: Print npm debug log
        run: cat /home/runner/.npm/_logs/2024-02-05T13_24_50_474Z-debug-0.log
        shell: bash
